---
title: "SNS Survey Analysis Notes"
output: 
  html_document:
          toc: true
          theme: united
          number_sections: true
---

```{r setup, include=FALSE,echo = F, message=F, warning=F}
knitr::opts_chunk$set(echo = F, message=F, warning=F)
load(paste0(getwd(),"/all_data.Rdata"))
require(knitr)
require(markdown)
require(ordinal)
```



# Data Summary

NA pattern unclear.

----
# FA Q8

3, 4 and 5 factors are acceptable. Shown are only 3 and 4 factors, as 5 appear too many for 9 variables.

```{r, echo=F,fig.align='center',fig.cap='Factor loadings'}
par(mfrow=c(1,2), mar = .pardefault$mar + c(0,2,0,2))
plot.matrix(q8fa3, cutoff=.4,col = grey.colors(2))
plot.matrix(q8fa4, cutoff=.4,col = grey.colors(2))
```

* Factor1 (Games): playgamesfriends, plagamesstranger, playgamesalone
* Factor2 (Spare time): killtime, browsenoreason, beentertained

Downloadmusic appears to be unrelated to the above identified latent variables.



```{r, echo=F,fig.align='center',fig.cap='Unique variance'}
par(mfrow=c(1,2), mar = .pardefault$mar - c(0,2,0,2))
my.barplot(q8fa3$uniquenesses,namez = names(q8fa3$uniquenesses),main="Unique variance")
my.barplot(q8fa4$uniquenesses,namez = names(q8fa4$uniquenesses),main="Unique variance")

```



----
# FA Q10

Minimum 3 factors required. 4 factors are too many.

```{r,fig.align='center',fig.cap='Loadings and unique variance'}
par(mar = .pardefault$mar + c(-2,4,-3,-2), mfrow=c(2,1))
plot.matrix(q10fa,cutoff=.33,col=grey.colors(2))
my.barplot(q10fa$uniquenesses,namez=names(q10fa$uniquenesses),main = "Unique variance")
```

----
# Analysis of Q19
Acceptable factors are 2 to 7.

```{r, fig.align='center', fig.cap='Summary of counts'}
par(mar = .pardefault$mar + c(2,0,0,8))
my.barplot.old(q19)
```
```{r, fig.align='center',fig.cap='Factor loadings'}
par(mar = .pardefault$mar + c(0,4,-2,0),mfrow=c(1,3))
plot.matrix(q19fa2,cutoff=.15,col=grey.colors(3))
plot.matrix(q19fa3,cutoff=.33,col=grey.colors(3))
plot.matrix(q19fa4,cutoff=.32,col=grey.colors(3))
```

```{r, fig.align='center',fig.cap='Unique variance'}
par(mar = .pardefault$mar + c(0,-2,-2,-1),mfrow=c(1,3))
my.barplot(q19fa2$uniquenesses,namez = names(q19fa2$uniquenesses),main="Unique variance")
my.barplot(q19fa3$uniquenesses,namez = names(q19fa3$uniquenesses),main="Unique variance")
my.barplot(q19fa4$uniquenesses,namez = names(q19fa4$uniquenesses),main="Unique variance")
```

----
# FA Q20

```{r, fig.align='center', fig.cap='Summary of counts'}
par(mar = .pardefault$mar + c(2,0,0,8))
my.barplot.old(q20)
```


```{r, fig.align='center',fig.cap='Factor loadings'}
par(mar = .pardefault$mar + c(0,4,-2,0),mfrow=c(2,2))
plot.matrix(q20fa2,cutoff=.15,col=grey.colors(3))
plot.matrix(q20fa3,cutoff=.15,col=grey.colors(3))
plot.matrix(q20fa4,cutoff=.15,col=grey.colors(3))
plot.matrix(q20fa5,cutoff=.15,col=grey.colors(3))
```

```{r, fig.align='center',fig.cap='Unique variance'}
par(mar = .pardefault$mar + c(0,-2,-2,-1),mfrow=c(2,2))
my.barplot(q20fa2$uniquenesses,namez = names(q20fa2$uniquenesses),main="Unique variance")
my.barplot(q20fa3$uniquenesses,namez = names(q20fa3$uniquenesses),main="Unique variance")
my.barplot(q20fa4$uniquenesses,namez = names(q20fa4$uniquenesses),main="Unique variance")
my.barplot(q20fa5$uniquenesses,namez = names(q20fa5$uniquenesses),main="Unique variance")
```

----

# Predictive models

## Predictive models: Q8 ~ Q7

```{r, echo = F, fig.align = 'center',fig.cap='Model predictive accuracy'}
par(mfrow=c(1,2), mar = .pardefault$mar + c(0,-1,0,-1))

plot(unlist(lapply(q7q8m1,function(x) eval.model(x)$total)),type="l",col=1
     ,ylim=c(.3,1),ylab="Accuracy",xaxt="n",xlab="",main="Q8 ~ Q7")
lines(unlist(lapply(q7q8m2,function(x) eval.model(x)$total)),col=2)
lines(unlist(lapply(q7q8m3,function(x) eval.model(x)$total)),col=3)
lines(unlist(lapply(q7q8m4,function(x) eval.model(x)$total)),col=4)
grid(10,2)
text(seq(1,length(q7q8m1),len=length(q7q8m1)),
     rep(par("usr")[3],length(q7q8m1)),
     labels=names(q7q8m1),xpd=NA,srt=45)
legend("top",horiz=T,c("logit","probit","cauchit","cloglog"),bty="n",fill=1:4,xpd=NA)

plot(unlist(lapply(q7q8m11,function(x) eval.model(x)$total)),type="l",col=1
     ,ylim=c(.3,1),ylab="Accuracy",xaxt="n",xlab="",main="Q7 ~ Q8")
lines(unlist(lapply(q7q8m21,function(x) eval.model(x)$total)),col=2)
lines(unlist(lapply(q7q8m31,function(x) eval.model(x)$total)),col=3)
lines(unlist(lapply(q7q8m41,function(x) eval.model(x)$total)),col=4)
grid(10,2)
text(seq(1,length(q7q8m11),len=length(q7q8m11)),
     rep(par("usr")[3],length(q7q8m11)),
     labels=names(q7q8m11),xpd=NA,srt=45)
legend("top",horiz=T,c("logit","probit","cauchit","cloglog"),bty="n",fill=1:4,xpd=NA)
```

```{r,fig.align='center'}
par(mfrow=c(1,2), mar = .pardefault$mar + c(0,-1,0,-1))
plot.clm(q7q8m3,lwd=5)
plot.clm(q7q8m31,lwd=5)
```


----

## Predictive models: Q10 ~ Q19

```{r, echo = F, fig.align = 'center',fig.cap='Model predictive accuracy'}
par(mfrow=c(1,2), mar = .pardefault$mar + c(0,-1,0,-1))

plot(unlist(lapply(q10q19m1,function(x) eval.model(x)$total)),type="l",col=1
     ,ylim=c(.3,1),ylab="Accuracy",xaxt="n",xlab="",main="Q8 ~ Q7")
lines(unlist(lapply(q10q19m2,function(x) eval.model(x)$total)),col=2)
lines(unlist(lapply(q10q19m3,function(x) eval.model(x)$total)),col=3)
lines(unlist(lapply(q10q19m4,function(x) eval.model(x)$total)),col=4)
grid(10,2)
text(seq(1,length(q10q19m1),len=length(q10q19m1)),
     rep(par("usr")[3],length(q10q19m1)),
     labels=names(q10q19m1),xpd=NA,srt=45)
legend("top",horiz=T,c("logit","probit","cauchit","cloglog"),bty="n",fill=1:4,xpd=NA)

plot(unlist(lapply(q10q19m11,function(x) eval.model(x)$total)),type="l",col=1
     ,ylim=c(.3,1),ylab="Accuracy",xaxt="n",xlab="",main="Q7 ~ Q8")
lines(unlist(lapply(q10q19m21,function(x) eval.model(x)$total)),col=2)
lines(unlist(lapply(q10q19m31,function(x) eval.model(x)$total)),col=3)
lines(unlist(lapply(q10q19m41,function(x) eval.model(x)$total)),col=4)
grid(10,2)
text(seq(1,length(q10q19m11),len=length(q10q19m11)),
     rep(par("usr")[3],length(q10q19m11)),
     labels=names(q10q19m11),xpd=NA,srt=45)
legend("top",horiz=T,c("logit","probit","cauchit","cloglog"),bty="n",fill=1:4,xpd=NA)
```

```{r,fig.align='center'}
par(mfrow=c(1,2), mar = .pardefault$mar + c(0,-1,0,-1))
plot.clm(q10q19m3,lwd=5)
plot.clm(q10q19m31,lwd=5)
```

----

## Predictive models:  Q10 ~ Q20

```{r, echo = F, fig.align = 'center',fig.cap='Model predictive accuracy'}
par(mfrow=c(1,2), mar = .pardefault$mar + c(0,-1,0,-1))

plot(unlist(lapply(q10q20m1,function(x) eval.model(x)$total)),type="l",col=1
     ,ylim=c(.3,1),ylab="Accuracy",xaxt="n",xlab="",main="Q8 ~ Q7")
lines(unlist(lapply(q10q20m2,function(x) eval.model(x)$total)),col=2)
lines(unlist(lapply(q10q20m3,function(x) eval.model(x)$total)),col=3)
lines(unlist(lapply(q10q20m4,function(x) eval.model(x)$total)),col=4)
grid(10,2)
text(seq(1,length(q10q20m1),len=length(q10q20m1)),
     rep(par("usr")[3],length(q10q20m1)),
     labels=names(q10q20m1),xpd=NA,srt=45)
legend("top",horiz=T,c("logit","probit","cauchit","cloglog"),bty="n",fill=1:4,xpd=NA)

plot(unlist(lapply(q10q20m11,function(x) eval.model(x)$total)),type="l",col=1
     ,ylim=c(.3,1),ylab="Accuracy",xaxt="n",xlab="",main="Q7 ~ Q8")
lines(unlist(lapply(q10q20m21,function(x) eval.model(x)$total)),col=2)
lines(unlist(lapply(q10q20m31,function(x) eval.model(x)$total)),col=3)
lines(unlist(lapply(q10q20m41,function(x) eval.model(x)$total)),col=4)
grid(10,2)
text(seq(1,length(q10q20m11),len=length(q10q20m11)),
     rep(par("usr")[3],length(q10q20m11)),
     labels=names(q10q20m11),xpd=NA,srt=45)
legend("top",horiz=T,c("logit","probit","cauchit","cloglog"),bty="n",fill=1:4,xpd=NA)
```

```{r,fig.align='center'}
par(mfrow=c(1,2), mar = .pardefault$mar + c(0,-1,0,-1))
plot.clm(q10q20m3,lwd=5)
plot.clm(q10q20m31,lwd=5)
```
----

## Predictive models: Q10 vs Q11
FA points towards 3 factors. 4 factors identify Q11 as a separate factor.

